### ISSUE TITLE
阅读和视频部分

### ISSUE THREAD

**Issue by MangoDong** [RuikaiWang/Study#2]
#是否是服务器验证时间？导致这部分代码失效呢？

**Comment by RuikaiWang** [comment]
这段时间一直在忙  他更新了一个头文件  我一会儿放上来

**Comment by ysymmsj** [comment]
谢谢两个大佬，可以用了。非常感谢

**Comment by tustxsfh** [comment]
我想研究一下代码，能告诉我增加积分的逻辑吗？

**Comment by ysymmsj** [comment]
昨天更新了一下，视频和阅读失效了。。。。

**Comment by MangoDong** [comment]
问题不大，加入了一个开始时间，抽时间改一下就好了。

--------------原始邮件--------------
发件人："ysymmsj "<notifications@github.com&gt;;
发送时间：2020年11月29日(星期天) 上午9:55
收件人："RuikaiWang/Study" <Study@noreply.github.com&gt;;
抄送："笔墨纸砚 "<1398083854@qq.com&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [RuikaiWang/Study] 阅读和视频部分 (#2)
-----------------------------------

 

 
昨天更新了一下，视频和阅读失效了。。。。

**Comment by MangoDong** [comment]
修复了，看更新吧

--------------原始邮件--------------
发件人："ysymmsj "<notifications@github.com&gt;;
发送时间：2020年11月29日(星期天) 上午9:55
收件人："RuikaiWang/Study" <Study@noreply.github.com&gt;;
抄送："笔墨纸砚 "<1398083854@qq.com&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [RuikaiWang/Study] 阅读和视频部分 (#2)
-----------------------------------

 

 
昨天更新了一下，视频和阅读失效了。。。。

**Comment by ysymmsj** [comment]
> 修复了，看更新吧
> […](#)
> --------------原始邮件--------------发件人："ysymmsj "<notifications@github.com>;发送时间：2020年11月29日(星期天)上午9:55收件人："RuikaiWang/Study" <Study@noreply.github.com>;抄送："笔墨纸砚"<1398083854@qq.com>;"State change " <state_change@noreply.github.com>;主题：Re: [RuikaiWang/Study]阅读和视频部分( #2 ) ----------------------- ------------昨天更新了一下，视频和阅读失效了。。。。— You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
用了你的新代码，能用了，谢谢大神。
