### ISSUE TITLE
楼主更新了重新抓下包吧

### ISSUE THREAD

**Issue by xuzilong19840304** [RuikaiWang/Study#4]
地址变了

**Comment by MangoDong** [comment]
代码没啥问题啊 正常

**Comment by wgw1206798585** [comment]
现在还是正常的？

**Comment by MangoDong** [comment]
是啊 没有什么问题 正常使用种，一天15分




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wgw1206798585"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 上午9:36
收件人: "RuikaiWang/Study"<Study@noreply.github.com&gt;; 
抄送: "笔墨纸砚"<1398083854@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RuikaiWang/Study] 楼主更新了重新抓下包吧 (#4)





 
现在还是正常的？

**Comment by Chris-z-su** [comment]
问一下这样安全吗？会不会被查到，你们使用的怎么样了

**Comment by wgw1206798585** [comment]
代码没问题的，哈哈，正常使用

**Comment by wgw1206798585** [comment]
代码没问题的，哈哈，正常使用

> 问一下这样安全吗？会不会被查到，你们使用的怎么样了

没啥事啊，我昨天开始用，好舒服啊

**Comment by RuikaiWang** [comment]
我自己暂时还能用,这脚本本来就是方便自己随手写的,很是粗糙,没想到还有人用....要是有空的话写个小程序版方便一下纯小白们.
