### ISSUE TITLE
2处更改

### ISSUE THREAD

**Issue by MangoDong** [RuikaiWang/Study#6]
密码登录使用了加密，可能是sha1，base64  未查dex
文章提交可能换了新网站！。

**Comment by MangoDong** [comment]
经查大概可能是AES/CBC/PKCS5Padding  RSA/ECB/PKCS1Padding密钥无法获取

**Comment by ysymmsj** [comment]
更新为333版本不能用了，提高安全。密码被加密了

**Comment by ysymmsj** [comment]
大神还会更新么。。。。

**Comment by MangoDong** [comment]
等待即可 密码加密很麻烦 需要逆向一下

**Comment by alpha87** [comment]
大佬，请问这个脚本是不是只要抓包把 Authorization 字段拷贝进去就能继续使用了？

我主要想用答题那部分代码，点赞浏览用的 autojs 模拟操作。

谢谢！

**Comment by xuzilong19840304** [comment]
大佬什么时候更新

**Comment by RuikaiWang** [comment]
> 等待即可 密码加密很麻烦 需要逆向一下

密码好说 文件已上传  文章那儿是地址改了的原因吗?  我周末抓下包详细看一下

**Comment by MangoDong** [comment]
> > 等待即可 密码加密很麻烦 需要逆向一下
> 
> 密码好说 文件已上传 文章那儿是地址改了的原因吗? 我周末抓下包详细看一下

大佬能加我一下QQ嘛  我已经上传了更新后的文件，QQ： MTM5ODA4Mzg1NA==  base64

**Comment by ysymmsj** [comment]
除了视频和文章阅读都可以用了，主要是那个答题能用就行，非常感谢大佬。

**Comment by alpha87** [comment]
现在软件的最新版本是 333 吗？

我现在打开软件显示 404，软件是准备更新接口了吗？

**Comment by RuikaiWang** [comment]
> > > 等待即可 密码加密很麻烦 需要逆向一下
> > 
> > 
> > 密码好说 文件已上传 文章那儿是地址改了的原因吗?我周末抓下包详细看一下
> 
> [QQ]，QQ：MTM5ODA4Mzg1NA+ base64

代码已合并 感谢,qq我加你了 你通过就好了
